config/routes.rb
Rails.application.routes.draw do
  resources :problems

  get 'pages/index'

  get 'pages/about'

end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render :show, status: :created, location: @problem }
      else
        format.html { render :new }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    respond_to do |format|
      if @problem.update(problem_params)
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @problem }
      else
        format.html { render :edit }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem.destroy
    respond_to do |format|
      format.html { redirect_to problems_url, notice: 'Problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:name, :email, :level, :question)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Problemruth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Problems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Level</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.name %></td>
        <td><%= problem.email %></td>
        <td><%= problem.level %></td>
        <td><%= problem.question %></td>
        <td><%= link_to 'Show', problem %></td>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @problem.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @problem.email %>
</p>

<p>
  <strong>Level:</strong>
  <%= @problem.level %>
</p>

<p>
  <strong>Question:</strong>
  <%= @problem.question %>
</p>

<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>